# Example gnuplot file to plot this data
#

        set timestamp 'generated by hamish at %F %T'
        set title 'Distance vs speed for each Last-Mile technology'
        set xlabel 'Meters'
        set ylabel 'Megabit/s'

        #set xtics out rotate by -15 86400
        set xtics out rotate by -15
        set mouse clipboardformat 5
        set grid ytics mytics lw 2, lw 1
        set grid xtics
        set autoscale fix

        set key left top Left title 'Legend' box 3

set style data lines

plot \
'gpon.0' using 2:3  title 'speed_mbps=gpon.0:3',\
'adsl1.2' using 2:3  title 'speed_mbps=adsl1.2:3',\
'adsl2.3' using 2:3  title 'speed_mbps=adsl2.3:3',\
'adsl2+.2' using 2:3  title 'speed_mbps=adsl2+.2:3',\
'vdsl2.5' using 2:3  title 'speed_mbps=vdsl2.5:3',\
'vdsl2.7' using 2:3  title 'speed_mbps=vdsl2.7:3'
pause mouse close

